sequential_4_4:
	gcc ./src/music_sequential.c -o ./sequential_4_4

grid_4_4:
	nvcc -I ./inc ./src/music_parallel_4_4.cu -o ./grid_4_4

grid_512_512:
	nvcc -I ./inc ./src/music_parallel_512_512.cu -o ./grid_512_512
