sequential_4_4:
	gcc ./src/music_sequential.c -o ./sequential_4_4

parallel_4_4:
	nvcc ./src/music_parallel_4_4.cu -o ./parallel_4_4

parallel_512_512:
	nvcc ./src/music_parallel_512_512.cu -o ./parallel_512_512
